/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'test-solutiondir.Debug+ARMCM7' 
 * Target:  'Debug+ARMCM7' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM7.h"



#endif /* RTE_COMPONENTS_H */
